-- Secuencia para generar IDs automáticamente
CREATE SEQUENCE student_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Tabla STUDENT
CREATE TABLE STUDENT (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100),
    LAST_NAME VARCHAR2(100)
);